language: java
jdk:
- openjdk7
- oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: U0vo627kO9/2hhrINtAm0m+QGo2aZL9UejLELxVN7no/g2SukvAVsMt4b3hiFM++9MnPDUjtkrjpb4zr5kvxYfUCPy1iKmcFCtxmVvlMSqUqe2Ltp2LpBwctMhWXSi9BJCFc98z+FU3TbixFZPgXvoI8T2LuUGTx0sLEa9xGAyrMs07gBPe1ur0E3Em7N5h65TyG+MiVKEWavAPRWuMS5MI/vJmFV0XXgqh9G/KkWI39qhP8CPEMOdPdu8LxRIyeVB0j8K2EyO57nZbmk46+ExBMu2eWEaRVfSARvXHMQMQX6pcUhu2ciTKXAKqMdwb5AcKJevwYA9etebjd5D6NkDJETSPWTdMc6q9w+k8vcgIQnc3iwm2YBc2OkJ6QLxFwU2sD6M6DDxDb8dhvRQ3H+0TVfxyEKIGP+a+iJQhTh0WfRE1UBCoCcs9zjGjIKZ06FDV2e0Y98r8J9ks8hsGcry1wR7Ejwbsn/1EY8oQbM6ji5p6WwgHHtJlV0aboqpViP0KnUhfRvP3vIkb0nkUTBPH/AtPjFf2dUZyypown7j6zcJo8rI1kE0+YciNC8JD8eoKXfS5DawAncja5/VAw4Ox/fQlvZJfD/6WBNX1SO0a4ANwAhmHCvmTc0TGlzKYD2V1CidUSRjURxzv2deD5TIaQQwHgU4SANUI1oZrzXYs=
